queue_rules:
  - name: default
    merge_method: squash
    queue_conditions:
      - check-success=build

pull_request_rules:
  - name: Make sure PRs are up to date before merging
    description: This automatically updates PRs when they are out-of-date with the base branch.
    conditions: []
    actions:
      update:

  - name: Automatically merge backports to releases on successful build
    conditions:
      - base~=^(release-)
      - head~=^mergify\/bp\/
      - author=mergify[bot]
    actions:
      queue:
        name: default
      label:
        add: ["auto merged"]

  - name: Automatically merge on CI success and review (no-squash)
    conditions:
      - base=main
      - label=ready to merge
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
      label:
        add: ["auto merged"]

  - name: Automatically merge on CI success and review (default squash)
    conditions:
      - base=main
      - label=ready to squash merge
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
      label:
        add: ["auto squash merged"]

priority_rules:
  - name: priority for queue `default`
    conditions:
      - queue-name=default
    priority: 2250